export default {
	TITLE: 'TITLE',
	FIRSTNAME: 'FIRSTNAME',
	LASTNAME: 'LASTNAME',
	BIRTHDAY: 'BIRTHDAY',
	NATIONALITY: 'NATIONALITY',
	CITIZEN_ID: 'CITIZEN_ID',
	GENDER: 'GENDER',
	MOBILE_PHONE: 'MOBILE_PHONE',
	PASSPORT: 'PASSPORT',
	EXPECTED_SALARY: 'EXPECTED_SALARY',
}
