export const actionType = {
	SET_TITLE: 'SET_TITLE',
	SET_FIRSTNAME: 'SET_FIRSTNAME',
	SET_LASTNAME: 'SET_LASTNAME',
	SET_BIRTHDAY: 'SET_BIRTHDAY',
	SET_NATIONALITY: 'SET_NATIONALITY',
	SET_CITIZEN_ID: 'SET_CITIZEN_ID',
	SET_GENDER: 'SET_GENDER',
	SET_MOBILE_PHONE: 'SET_MOBILE_PHONE',
}
